AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-rspec
  - rubocop-rake

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5



# Disable index-related warnings for biblical references (chapter:verse format is natural)
RSpec/IndexedLet:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# Allow longer methods for complex parsing logic
Metrics/MethodLength:
  Max: 25

# Allow larger classes for data-heavy classes
Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/pericope/pericope.rb'        # Main class with comprehensive parsing functionality
    - 'lib/pericope/math_operations.rb' # Mathematical operations class with complete feature set

# Allow larger modules for data modules
Metrics/ModuleLength:
  Max: 200

# Allow higher complexity for parsing methods
Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Allow more memoized helpers in specs for biblical references
RSpec/MultipleMemoizedHelpers:
  Max: 10
