name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop --format github

    - name: Run RSpec
      run: bundle exec rspec --format progress